language: node_js
node_js:
- '10'
env:
  global:
    - secure: bOThtfGKwzKz4ZYjTRF61VelU2MMCNU5Y0DA3oFhJulk8kF2wXwojGJeK8K16Ny6yn5suVW49SUqdNh/RasyaWGwRiAGFPacUTwMW7PccMZ2OIEtFvrEe0G2fMrMwfd9wUtm7llGNe/4WDYUodXMTfwQl0gBPtqK+y87aZbKchpqoQlNKMHnBskA3VdZ5WRzCHZkP0eQheI44LKsmDimwLK5YbNoH2vXU4wv23tiBSWmgNk1UHWMyz/SGoDo8AkP51Y5ej8MbQOxHzfB4S+x0yPs7kEFQ9ieNL0SFzeFd3LET8c06YhADm6bGfylPzd/h8//vN6JzNAAtVBeI72kno8FCRw2/nod6ZGlrKzUoZfELB3qMnhqtxXnyDu9E2hHgjZpWPxgnTU5mig8Tn+p+Nl7VOQ96njmGomylmRvSw8yjc9OinBcrzG2WP9c+kKhkFmLCJhg7rwxzhYcggPaLdPXY7vjsaEtb+FROX98Qgq6ydk7m0Vpfep1M1Yn0hHGnCR7YSeiOzQcza+VgxKKehKC3DIUvGQUKSqvCOqsJruzJTouptp8We9e1lIFnpKvCPRgd4SNqxytCd6MNW/ncOJrtYQhLuI2EMmhJYcgfra/Wt6yVu8m2NTgTUy8B9tCQwyiT5MqcXTs0TxCwqZAOY4mWP0M8Ial5Q4HTc3kPPo=
deploy:
  provider: releases
  api_key:
    secure: UBDeFtv8vBWhWy0FvAFEnwKTfldPqRuQ3M0mSljeSDWJMeKgW28ew4QCYTVXwmWPpJLPZLObyq19R6DW0qT3VM52/eKtGZwOLRIhgtCLUUu8jY6dIx9b411OQ990aAAS06HJ1eomrpFXIoVrz8wiPpwRaPYFW1d9H9J6v8cn6XSmujO1bi/sagAnE4YmHilgC/zCbF63lExAOJd/sAfJTSzWUP8RTB7HJ4WZvPPzswjFouunPOXSF5tZREoFIDX1iuzvunOdpcLzuiP22VRTWYd1rHYyHj5WOxWki57HrK+BaL7YUpcvRJ4qspEpxwpUTJCLP3qhyPXvUBK1BpzHi3r6RQl1ts23teVBtfYMZT8x/vPLizj46w/8aaRbWBxYL7LGwiTnCPXz5bbICdDJ9WrVMa0tYb+IetMDhG3Y/x7XpQuVf15H0BnbHhpoqZFQZF1aT52/bC5osQ2lzNnTr6noLpueT52UwMZ8kK59qGmg1q0bkIMhJkKjf23Y+VAk7IFZ1CwLqnofqPcJj7uG8MfVbnDV+Q94zd1s9bpNa9FvlHvzGTLb+yMfZ3Zr3Y0uE7TkVMMWt3VKjIJ7BC3m5C50Cc/bDn8zqdwc4suetlLLZi9YomMgvmOeeFMG4uQfi4Ma0CF1oyuXnacnB7WbuWOsPoBah4WtbDLZoupPE98=
  file_glob: true
  file: build/sublime/*
  skip_cleanup: true
  on:
    tags: true
after_deploy:
  - ./push-assets.sh
